Update Dockerfile base image to compatible nix version since attribute names have changed
Fixes the following error:

warning: unknown setting 'accept-flake-config'
warning: Git tree '/app' is dirty
error: flake 'git+file:///app' does not provide attribute 'packages.x86_64-linux.defaultPackage.x86_64-linux', 'legacyPackages.x86_64-linux.defaultPackage.x86_64-linux' or 'defaultPackage.x86_64-linux'